#!/bin/sh

YEAR=$(date '+%Y')
MONTH=$(date '+%m')
FULL_DATE=$(date '+%F')

# SNAR="$1"/"$YEAR"-"$MONTH".snar

# Validate parameter is a directory
if [[ -d $1 ]]; then
  echo "Backing up /home ..."
else
  echo "$1 is not a valid directory"
  exit 1
fi

# Create tar and pipe through GPG
# Incremental backups are currently disabled
#     -g "$SNAR" \
tar -czvf - \
      -X ~/backup_exclude.txt \
      -T ~/backup_include.txt \
| gpg -ser aidan@loughran.dev \
      --cipher-algo AES256 \
      -o "$1/$FULL_DATE.tgz.bin"

# TODO: check output file exists, ask to overwrite or abort
