#!/bin/sh

OUTPUT_PATH="Backups/$(date '+%F')\ PC\ Artix.txz.gpg"
FULL_PATH="/mnt/nas/$OUTPUT_PATH"

# Create encrypted, compressed tar and save to remote
  tar cvf - \
      --ignore-failed-read \
      --exclude /home/aidan/Shared \
      --exclude .angular \
      --exclude .cache \
      --exclude .cargo \
      --exclude .electron-gyp \
      --exclude .gradle \
      --exclude .npm \
      --exclude cache \
      --exclude Cache \
      --exclude node_modules \
      /home \
| xz  -9 -T0 \
| gpg -er D3C4963B -z0 -o - \
| ssh anon@srv2 "cat > $FULL_PATH"

# Pause because server has ssh auth session timeout
read -p "Press enter to begin upload"

# Push backup to the cloud via server
ssh -t admin@srv2 "sudo rclone -P copyto --config=/root/.config/rclone/rclone.conf $FULL_PATH proton:$OUTPUT_PATH"
