#!/bin/sh

# Script is ran manually after cd-ing into mounted
# dir where .SeedVaultAndroidBackup/ can be found

# Ensure NAS filesystem is mounted
$SCRIPT_DIR/mount-nas

# Create tar and pipe it through GPG
tar -czvf - .SeedVaultAndroidBackup | gpg \
  -se -r aidan@loughran.dev -z 0 \
  -o /mnt/nas/backup/android/aidan/$(date '+%F').tgz.bin
