#!/bin/sh

# Mount NAS filesystem
$SCRIPT_DIR/mount-nas

# Mount remote home if not mounted
REMOTE_HOME_MOUNTPOINT=~/Shared
if ! mountpoint -q $REMOTE_HOME_MOUNTPOINT; then
  sshfs -C -o follow_symlinks server:/mnt/nas/main/aidan $REMOTE_HOME_MOUNTPOINT
fi
